"""empty message

Revision ID: ac86c7bbeb7a
Revises: 8126e8cfa95d
Create Date: 2024-05-25 15:47:18.394469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac86c7bbeb7a'
down_revision = '8126e8cfa95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('dtNascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario')
    # ### end Alembic commands ###
