"""empty message

Revision ID: b581e83aa67b
Revises: af4dd7cee757
Create Date: 2024-05-25 10:05:11.457340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b581e83aa67b'
down_revision = 'af4dd7cee757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projeto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'projeto', ['projeto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('projeto_id')

    # ### end Alembic commands ###
